### PR TITLE
feat: fix navbar rendering for all different account types

### LINKED ISSUE #223: Navigation for student accounts
Navigation bar when logged in as a student should only show his planning and the logout button. Currently shows everything.

### LINKED ISSUE #224: Navigation for syndicus accounts
Navigation bar when logged in as a syncidus should only show his buildings, allow to edit his buildings, show issues, ... Currently shows everything.

### PR DESCRIPTION
**Pull request by MaximStockmans**
Currently redirects logged in users to /home which redirects them to the correct starting page. Would like to redirect them to / instead but / gets redirected to /login automatically and I can't find how to disable this. Tried removing the config in next.config.js but did not fix.

Closes #223 
Closes #224

### CODE REVIEW

**Comment by MaximStockmans** [comment]
Should be updated to support Lander's changes for the mobile navbar support

**Comment by MaximStockmans** [comment]
Currently the bottom mobile navbar for student accounts and syndicus is a little weird, since it only contains one icon. But this will be fixed once account pages for individual accounts are implemented (planned for this week on the KANBAN board)

File: frontend/src/pages/home.tsx [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+            if (userData.data.student && !userData.data.student.is_super_student) {
+                router.push('/my-schedule');
+            } else if (userData.data.syndicus) {
+                router.push('/my-buildings');
+            } else {
+                router.push('/live_routes');
+            }
+        }
+    }, [userData]);
+    return (<div></div>);
```
Comment (ChewingBever) [inline frontend/src/pages/home.tsx:32]: Is this supposed to just be empty?

Comment (MaximStockmans) [reply frontend/src/pages/home.tsx:32]: Yes, the only function of this page is to redirect after login. The callback from next-auth does not support dynamic routes, so we have to redirect after the redirect from the login.

So the user goes to /login -> redirected to /home which redirects to the correct starting page for the user for example /my-buildings or /live-routes

Comment (ChewingBever) [reply frontend/src/pages/home.tsx:32]: I see, and what about the TODO's in certain files?

Comment (MaximStockmans) [reply frontend/src/pages/home.tsx:32]: This is because the page is not implemented yet. There is no my-buildings yet, and no my-schedule (but this will be added once I update @jchetti's PR and add his integration in this routing)

Comment (ChewingBever) [reply frontend/src/pages/home.tsx:32]: Alright, so then these are okay to be merged in dev for now?

Comment (MaximStockmans) [reply frontend/src/pages/home.tsx:32]: Yes is functional on it's own, but https://github.com/SELab-2/Dr-Trottoir-3/pull/251 will have to be updated before merge

**Review by ChewingBever — APPROVED** [review]

**Review by jchetti — APPROVED** [review]
